### ISSUE TITLE
Moderation / Safety section.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [own-me/promo#5]
Talk about our moderation process and verification of legal photography.

**Comment by ChristopherTrimboli** [comment]
@SylviaMakuch You can work with me on this one, we will design the Figma and you can implement the design in the website.

**Comment by SylviaMakuch** [comment]
Please invite me to the figma project, thanks.

**Comment by ChristopherTrimboli** [comment]
![Screenshot 2021-12-18 233639](https://user-images.githubusercontent.com/27584221/146667458-7482fac8-a0f8-4947-bd49-4c4c98ae1128.png)

this is our mockup, I don't really like the colors but layout is OK

**Comment by ChristopherTrimboli** [comment]
done!
